"use client";

import { useActionState } from "react";
import { acceptActivityAction, discardAndRegenerateAction, editAndAcceptActivityAction, ratePreApplicationAction } from "@/lib/actions/activities";
import type { ActionState } from "@/lib/actions/auth";
import type { GeneratedActivity } from "@/lib/schemas/activity";
import { FormMessage } from "@/components/ui/form-message";
import { SubmitButton } from "@/components/ui/submit-button";

const discardReasons = ["Demasiado difícil","Demasiado sencilla","Demasiado larga","Requiere demasiados materiales","No se adapta al grupo","No se adapta a un alumno","No es suficientemente dinámica","Instrucciones confusas","Otra razón"];
export function ActivityCard({ optionId, requestId, status, rating, activity }: { optionId: string; requestId: string; status: string; rating: number | null; activity: GeneratedActivity }) {
  const [editState, editAction] = useActionState(editAndAcceptActivityAction, {} as ActionState);
  return <article className={`card overflow-hidden ${status === "discarded" ? "opacity-60" : ""}`}>
    <div className="border-b border-[#dce4df] p-6"><div className="flex flex-wrap items-center justify-between gap-3"><span className="chip capitalize">{activity.activityType}</span><span className="muted text-sm">{activity.durationMinutes} min · {status}</span></div><h2 className="mt-5 text-2xl font-black tracking-tight">{activity.title}</h2><p className="muted mt-3 leading-7">{activity.objective}</p></div>
    <div className="grid gap-6 p-6 lg:grid-cols-2"><section><h3 className="font-extrabold">Materiales</h3><ul className="muted mt-2 list-disc space-y-1 pl-5 text-sm">{activity.materials.map((item) => <li key={item}>{item}</li>)}</ul></section><section><h3 className="font-extrabold">Preparación</h3><ul className="muted mt-2 list-disc space-y-1 pl-5 text-sm">{activity.preparation.map((item) => <li key={item}>{item}</li>)}</ul></section></div>
    <div className="border-y border-[#dce4df] bg-[#fbfaf6] p-6"><h3 className="font-extrabold">Pasos principales</h3><ol className="mt-4 space-y-4">{activity.steps.map((step) => <li className="grid grid-cols-[32px_1fr] gap-3" key={`${step.order}-${step.instruction}`}><span className="grid size-8 place-items-center rounded-full bg-[#176b5c] text-sm font-bold text-white">{step.order}</span><div><p>{step.instruction}</p><p className="muted mt-1 text-xs">{step.estimatedMinutes} min · Apoyo: {step.educatorSupport}</p></div></li>)}</ol></div>
    <div className="grid gap-6 p-6 lg:grid-cols-2"><section><h3 className="font-extrabold">Adaptaciones por perfil</h3><div className="mt-3 grid gap-3">{activity.studentAdaptations.map((adaptation) => <div className="rounded-xl bg-[#edf6f1] p-4" key={adaptation.studentKey}><p className="text-sm font-bold">{adaptation.studentKey}</p><ul className="muted mt-2 list-disc space-y-1 pl-4 text-sm">{adaptation.recommendations.map((item) => <li key={item}>{item}</li>)}</ul></div>)}</div></section><section><h3 className="font-extrabold">Evaluación formativa</h3><p className="mt-3 text-sm font-bold">Evidencias</p><p className="muted mt-1 text-sm">{activity.assessment.evidence.join(" · ")}</p><p className="mt-3 text-sm font-bold">Formas de respuesta</p><p className="muted mt-1 text-sm">{activity.assessment.responseOptions.join(" · ")}</p></section></div>
    <div className="border-t border-[#dce4df] p-6"><p className="text-sm"><strong>Por qué se propone:</strong> {activity.rationale}</p>{activity.safetyNotes.length > 0 && <p className="muted mt-3 text-xs"><strong>Revisa:</strong> {activity.safetyNotes.join(" · ")}</p>}</div>
    {status !== "discarded" && <div className="no-print grid gap-4 border-t border-[#dce4df] bg-white p-6"><div className="flex flex-wrap gap-2"><form action={acceptActivityAction}><input type="hidden" name="optionId" value={optionId}/><button className="button" type="submit">Aceptar actividad</button></form><form action={ratePreApplicationAction} className="flex items-center gap-2"><input type="hidden" name="optionId" value={optionId}/><input type="hidden" name="requestId" value={requestId}/><label className="text-sm font-bold" htmlFor={`rating-${optionId}`}>Valoración previa</label><select className="input !w-auto" id={`rating-${optionId}`} name="rating" defaultValue={rating ?? ""} onChange={(event) => event.currentTarget.form?.requestSubmit()}><option value="">—</option>{[1,2,3,4,5].map((star) => <option key={star} value={star}>{star} ★</option>)}</select></form></div>
      <details><summary className="cursor-pointer font-bold text-[#176b5c]">Editar antes de aceptar</summary><form action={editAction} className="mt-4 grid gap-4 rounded-xl bg-[#edf6f1] p-4"><input type="hidden" name="optionId" value={optionId}/><div className="field"><label>Título</label><input className="input" name="title" defaultValue={activity.title}/></div><div className="field"><label>Objetivo</label><textarea className="input" name="objective" defaultValue={activity.objective}/></div><div className="field"><label>Justificación</label><textarea className="input" name="rationale" defaultValue={activity.rationale}/></div><FormMessage state={editState}/><SubmitButton>Guardar edición y aceptar</SubmitButton></form></details>
      <details><summary className="cursor-pointer font-bold text-[#a23b3b]">Descartar y generar otra</summary><form action={discardAndRegenerateAction} className="mt-4 flex flex-wrap gap-3"><input type="hidden" name="optionId" value={optionId}/><input type="hidden" name="requestId" value={requestId}/><select className="input flex-1" name="discardReason" required><option value="">Selecciona el motivo</option>{discardReasons.map((reason) => <option key={reason}>{reason}</option>)}</select><button className="button button-danger" type="submit">Descartar y regenerar</button></form></details></div>}
  </article>;
}
